#!/bin/sh

for FILE in `git diff --cached --name-only`; do
	if [ -f $FILE ] && ! [ -L $FILE ]; then
		case $FILE in
			*.rs)
				rustfmt +nightly --unstable-features --skip-children $FILE ;;
		esac
		perl -pi -e 'chomp if eof' $FILE
		git add $FILE
	fi
done