[workspace]
members = [".", "src/macros"]
resolver = "2"

[workspace.package]
authors = ["Sʜɪᴍᴜʀᴀ Yū <mail@yuhr.org>"]
categories = ["parsing"]
description = "Monotonic chart parsing."
edition = "2021"
exclude = ["*.toml", ".*", "justfile"]
keywords = ["parser"]
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/yuhr/ruleset"
version = "2.0.1"

[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
name = "ruleset"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.95"
comfy-table = "7.1.3"
derive-where = "1.2.7"
either = "1.13.0"
ruleset-macros = { path = "src/macros", version = "=2.0.1" }
serde = { version = "1.0.217", features = ["derive"], optional = true }
stable_try_trait_v2 = "1.75.1"
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }

[dev-dependencies]
criterion = "0.5.1"
insta = "1.42.0"
ruleset = { path = ".", features = ["serde"] }
serde = "1.0.217"
serde_yaml = "0.9.34"
stdext = "0.3.3"

[lib]
doctest = false

[[bench]]
harness = false
name = "parsing"